# Generated by Django 4.2.8 on 2023-12-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MailSettings",
            fields=[
                (
                    "mail_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Mail ID"
                    ),
                ),
                (
                    "mail_host",
                    models.CharField(max_length=255, verbose_name="Mail Host"),
                ),
                (
                    "mail_port",
                    models.CharField(max_length=255, verbose_name="Mail Port"),
                ),
                (
                    "mail_use_tls",
                    models.BooleanField(default=True, verbose_name="Mail TLS"),
                ),
                (
                    "mail_username",
                    models.CharField(max_length=255, verbose_name="Mail Username"),
                ),
                (
                    "mail_password",
                    models.CharField(max_length=255, verbose_name="Mail Password"),
                ),
                (
                    "mail_from",
                    models.CharField(max_length=255, verbose_name="Mail From"),
                ),
                (
                    "mail_def_from",
                    models.CharField(max_length=255, verbose_name="Mail Default From"),
                ),
            ],
            options={
                "verbose_name": "Mail Ayarları",
                "verbose_name_plural": "Mail Ayarları",
            },
        ),
    ]
