# Generated by Django 4.2.8 on 2023-12-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0003_alter_mailsettings_mail_port"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailsettings",
            name="mail_port",
            field=models.IntegerField(verbose_name="Mail Port"),
        ),
    ]
