# Generated by Django 4.2.8 on 2023-12-14 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0011_alter_schoolpopup_popup_title"),
        ("management", "0004_alter_mailsettings_mail_port"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "free_shipping_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Ücretsiz Kargo Limiti",
                    ),
                ),
                (
                    "shipping_cost_type",
                    models.CharField(
                        choices=[
                            ("Kargo Ücreti Yok", "Kargo Ücreti Yok"),
                            ("Sabit Kargo Ücreti", "Sabit Kargo Ücreti"),
                            ("Ürün Bazlı Ücretlendirme", "Ürün Bazlı Ücretlendirme"),
                        ],
                        default="Sabit Kargo Ücreti",
                        max_length=100,
                        verbose_name="Kargo Ücreti Tipi",
                    ),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Kargo Ücreti",
                    ),
                ),
                (
                    "return_shipping_cost_type",
                    models.CharField(
                        choices=[
                            ("İade Kargo Ücreti Yok", "İade Kargo Ücreti Yok"),
                            ("Sabit İade Kargo Ücreti", "Sabit İade Kargo Ücreti"),
                            (
                                "Ürün Bazlı İade Ücretlendirme",
                                "Ürün Bazlı İade Ücretlendirme",
                            ),
                        ],
                        default="Sabit İade Kargo Ücreti",
                        max_length=100,
                        verbose_name="İade Kargo Ücreti Tipi",
                    ),
                ),
                (
                    "return_shipping_payment",
                    models.CharField(
                        choices=[
                            ("Peşin Ödeme", "Peşin Ödeme"),
                            ("İade Tutarından Düş", "İade Tutarından Düş"),
                        ],
                        default="Peşin Ödeme",
                        max_length=100,
                        verbose_name="İade Kargo Ödemesi",
                    ),
                ),
                (
                    "return_shipping_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="İade Kargo Ücreti",
                    ),
                ),
                (
                    "change_shipping_cost_type",
                    models.CharField(
                        choices=[
                            ("Değişim Kargo Ücreti Yok", "Değişim Kargo Ücreti Yok"),
                            (
                                "Sabit Değişim Kargo Ücreti",
                                "Sabit Değişim Kargo Ücreti",
                            ),
                            (
                                "Ürün Bazlı Değişim Ücretlendirme",
                                "Ürün Bazlı Değişim Ücretlendirme",
                            ),
                        ],
                        default="Sabit Değişim Kargo Ücreti",
                        max_length=100,
                        verbose_name="Değişim Kargo Ücreti Tipi",
                    ),
                ),
                (
                    "change_shipping_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Değişim Kargo Ücreti",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schools.schools",
                        verbose_name="Okul",
                    ),
                ),
            ],
        ),
    ]
