# Generated by Django 4.2.8 on 2023-12-15 07:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0005_shippingcost"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shippingcost",
            options={
                "verbose_name": "Kargo Ayarları",
                "verbose_name_plural": "Kargo Ayarları",
            },
        ),
    ]
