# Generated by Django 4.2.7 on 2023-12-16 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0011_alter_schoolpopup_popup_title"),
        ("management", "0006_alter_shippingcost_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscountManagement",
            fields=[
                ("pm_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "double_discount",
                    models.BooleanField(
                        default=True,
                        help_text="Bu ayar açık olduğunda Özel İndirim ve İndirim Kuponu aynı anda uygulanacaktır. Bu ayar kapalı ise sepette sadece önceğili 1 olan indirim uygulanacaktır.",
                        verbose_name="Özel İndirim & İndirim Kuponu",
                    ),
                ),
                (
                    "sd_priority",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="1: Yüksek Öncelik | 2: Düşük Öncelik",
                        verbose_name="Özel İndirim Önceliği",
                    ),
                ),
                (
                    "dc_priority",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="1: Yüksek Öncelik | 2: Düşük Öncelik",
                        verbose_name="İndirim Kuponu Önceliği",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schools.schools",
                    ),
                ),
            ],
            options={
                "verbose_name": "İndirim Önceliği Ayarı",
                "verbose_name_plural": "İndirim Önceliği Ayarları",
            },
        ),
    ]
