# Generated by Django 5.0 on 2024-02-12 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("schools", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailSettings",
            fields=[
                (
                    "mail_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Mail ID"
                    ),
                ),
                (
                    "mail_host",
                    models.CharField(max_length=255, verbose_name="Mail Host"),
                ),
                ("mail_port", models.IntegerField(verbose_name="Mail Port")),
                (
                    "mail_use_tls",
                    models.BooleanField(default=True, verbose_name="Mail TLS"),
                ),
                (
                    "mail_username",
                    models.CharField(max_length=255, verbose_name="Mail Username"),
                ),
                (
                    "mail_password",
                    models.CharField(max_length=255, verbose_name="Mail Password"),
                ),
                (
                    "mail_from",
                    models.CharField(max_length=255, verbose_name="Mail From"),
                ),
                (
                    "mail_def_from",
                    models.CharField(max_length=255, verbose_name="Mail Default From"),
                ),
            ],
            options={
                "verbose_name": "Mail Ayarları",
                "verbose_name_plural": "Mail Ayarları",
            },
        ),
        migrations.CreateModel(
            name="PaymentGateways",
            fields=[
                (
                    "pg_id",
                    models.BigAutoField(primary_key=True, serialize=False, unique=True),
                ),
                (
                    "payment_gateway",
                    models.CharField(
                        choices=[
                            ("iyzico", "IyziPay"),
                            ("param", "Param"),
                            ("ipara", "iPara"),
                        ],
                        max_length=255,
                        verbose_name="Ödeme Sağlayıcısı",
                    ),
                ),
                (
                    "payment_base_url",
                    models.CharField(max_length=1000, verbose_name="API Url"),
                ),
                (
                    "payment_api_key",
                    models.CharField(
                        blank=True, max_length=1000, null=True, verbose_name="API Key"
                    ),
                ),
                (
                    "payment_secret",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="API Secret Key",
                    ),
                ),
                (
                    "payment_username",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="API Client Username",
                    ),
                ),
                (
                    "payment_password",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="API Client Password",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ödeme Sağlayıcı",
                "verbose_name_plural": "Ödeme Sağlayıcıları",
            },
        ),
        migrations.CreateModel(
            name="DiscountManagement",
            fields=[
                ("pm_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "double_discount",
                    models.BooleanField(
                        default=True,
                        help_text="Bu ayar açık olduğunda Özel İndirim ve İndirim Kuponu aynı anda uygulanacaktır. Bu ayar kapalı ise sepette sadece önceğili 1 olan indirim uygulanacaktır.",
                        verbose_name="Özel İndirim & İndirim Kuponu",
                    ),
                ),
                (
                    "sd_priority",
                    models.CharField(
                        choices=[("Yüksek", "Yüksek"), ("Düşük", "Düşük")],
                        default="Yüksek",
                        help_text="1: Yüksek Öncelik | 2: Düşük Öncelik",
                        max_length=100,
                        verbose_name="Özel İndirim Önceliği",
                    ),
                ),
                (
                    "dc_priority",
                    models.CharField(
                        choices=[("Yüksek", "Yüksek"), ("Düşük", "Düşük")],
                        default="Düşük",
                        help_text="1: Yüksek Öncelik | 2: Düşük Öncelik",
                        max_length=100,
                        verbose_name="İndirim Kuponu Önceliği",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schools.schools",
                    ),
                ),
            ],
            options={
                "verbose_name": "İndirim Önceliği Ayarı",
                "verbose_name_plural": "İndirim Önceliği Ayarları",
            },
        ),
        migrations.CreateModel(
            name="ShippingCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "free_shipping_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Ücretsiz Kargo Limiti",
                    ),
                ),
                (
                    "shipping_cost_type",
                    models.CharField(
                        choices=[
                            ("Kargo Ücreti Yok", "Kargo Ücreti Yok"),
                            ("Sabit Kargo Ücreti", "Sabit Kargo Ücreti"),
                            ("Ürün Bazlı Ücretlendirme", "Ürün Bazlı Ücretlendirme"),
                        ],
                        default="Sabit Kargo Ücreti",
                        max_length=100,
                        verbose_name="Kargo Ücreti Tipi",
                    ),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Kargo Ücreti",
                    ),
                ),
                (
                    "return_shipping_cost_type",
                    models.CharField(
                        choices=[
                            ("İade Kargo Ücreti Yok", "İade Kargo Ücreti Yok"),
                            ("Sabit İade Kargo Ücreti", "Sabit İade Kargo Ücreti"),
                            (
                                "Ürün Bazlı İade Ücretlendirme",
                                "Ürün Bazlı İade Ücretlendirme",
                            ),
                        ],
                        default="Sabit İade Kargo Ücreti",
                        max_length=100,
                        verbose_name="İade Kargo Ücreti Tipi",
                    ),
                ),
                (
                    "return_shipping_payment",
                    models.CharField(
                        choices=[
                            ("Peşin Ödeme", "Peşin Ödeme"),
                            ("İade Tutarından Düş", "İade Tutarından Düş"),
                        ],
                        default="Peşin Ödeme",
                        max_length=100,
                        verbose_name="İade Kargo Ödemesi",
                    ),
                ),
                (
                    "return_shipping_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="İade Kargo Ücreti",
                    ),
                ),
                (
                    "change_shipping_cost_type",
                    models.CharField(
                        choices=[
                            ("Değişim Kargo Ücreti Yok", "Değişim Kargo Ücreti Yok"),
                            (
                                "Sabit Değişim Kargo Ücreti",
                                "Sabit Değişim Kargo Ücreti",
                            ),
                            (
                                "Ürün Bazlı Değişim Ücretlendirme",
                                "Ürün Bazlı Değişim Ücretlendirme",
                            ),
                        ],
                        default="Sabit Değişim Kargo Ücreti",
                        max_length=100,
                        verbose_name="Değişim Kargo Ücreti Tipi",
                    ),
                ),
                (
                    "change_shipping_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Değişim Kargo Ücreti",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schools.schools",
                        verbose_name="Okul",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kargo Ayarları",
                "verbose_name_plural": "Kargo Ayarları",
            },
        ),
    ]
