# Generated by Django 4.2.6 on 2023-10-23 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CombinationProduct",
            fields=[
                ("CProductID", models.AutoField(primary_key=True, serialize=False)),
                ("SProductInfo", models.JSONField()),
                ("CProductQuantity", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "ProductCategoryID",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("CategoryName", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ProductCategorySizes",
            fields=[
                ("CategorySizeID", models.AutoField(primary_key=True, serialize=False)),
                ("ProductSize", models.CharField(max_length=100)),
                (
                    "ProductCategoryID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.productcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductPrice",
            fields=[
                ("PriceID", models.AutoField(primary_key=True, serialize=False)),
                ("SalePrice", models.DecimalField(decimal_places=2, max_digits=10)),
                ("StrikedPrice", models.IntegerField()),
                ("DiscountRatio", models.IntegerField()),
                ("DiscountPrice", models.IntegerField()),
                ("DiscountType", models.CharField(max_length=100)),
                ("TaxPrice", models.CharField(max_length=100)),
                ("CombinePriceInfo", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="ProductStock",
            fields=[
                ("StockID", models.AutoField(primary_key=True, serialize=False)),
                ("RealStock", models.IntegerField()),
                ("SaleStock", models.IntegerField()),
                ("ReservedStock", models.IntegerField()),
                ("AcceptStock", models.IntegerField()),
                ("ReturnStock", models.IntegerField()),
                ("CancelStock", models.IntegerField()),
                ("PreproductionStock", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="SetProduct",
            fields=[
                ("SetID", models.AutoField(primary_key=True, serialize=False)),
                ("SProductInfo", models.JSONField()),
                ("SProductQuantity", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                ("ProductID", models.AutoField(primary_key=True, serialize=False)),
                ("product_type", models.CharField(max_length=100)),
                ("product_production_name", models.CharField(max_length=255)),
                ("product_name", models.CharField(max_length=255)),
                ("product_web_name", models.CharField(max_length=255)),
                ("product_production_date", models.DateField()),
                ("SKU_code", models.CharField(max_length=100)),
                ("barcode", models.CharField(max_length=100)),
                ("model_code", models.CharField(max_length=100)),
                ("product_color", models.CharField(max_length=100)),
                ("book_type", models.CharField(max_length=100)),
                ("product_state", models.IntegerField()),
                ("product_genre", models.CharField(max_length=100)),
                ("product_class", models.CharField(max_length=100)),
                ("product_level", models.CharField(max_length=100)),
                ("product_image", models.URLField()),
                ("product_measure_unit", models.CharField(max_length=100)),
                ("product_created_at", models.DateTimeField()),
                ("product_last_update", models.DateTimeField()),
                ("product_season", models.DateField()),
                ("product_change_limit", models.JSONField()),
                (
                    "CategorySizeID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.productcategorysizes",
                    ),
                ),
                (
                    "PriceID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.productprice",
                    ),
                ),
                (
                    "ProductCategoryID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.productcategory",
                    ),
                ),
                (
                    "StockID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.productstock",
                    ),
                ),
            ],
        ),
    ]
