# Generated by Django 4.2.6 on 2023-10-24 19:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CombinationProduct",
        ),
        migrations.RemoveField(
            model_name="productcategorysizes",
            name="ProductCategoryID",
        ),
        migrations.RemoveField(
            model_name="products",
            name="CategorySizeID",
        ),
        migrations.RemoveField(
            model_name="products",
            name="PriceID",
        ),
        migrations.RemoveField(
            model_name="products",
            name="ProductCategoryID",
        ),
        migrations.RemoveField(
            model_name="products",
            name="StockID",
        ),
        migrations.DeleteModel(
            name="SetProduct",
        ),
        migrations.DeleteModel(
            name="ProductCategory",
        ),
        migrations.DeleteModel(
            name="ProductCategorySizes",
        ),
        migrations.DeleteModel(
            name="ProductPrice",
        ),
        migrations.DeleteModel(
            name="Products",
        ),
        migrations.DeleteModel(
            name="ProductStock",
        ),
    ]
