# Generated by Django 4.2.8 on 2023-12-31 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0016_alter_combinationproduct_options_and_more"),
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Sevkiyat Adı")),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("Tır", "Tır"),
                            ("Kamyon", "Kamyon"),
                            ("Kargo", "Kargo"),
                        ],
                        max_length=50,
                        verbose_name="Araç Tipi",
                    ),
                ),
                ("address", models.CharField(max_length=200, verbose_name="Adres")),
                ("phone", models.CharField(max_length=20, verbose_name="Telefon")),
                ("fax", models.CharField(max_length=20, verbose_name="Faks")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.warehouse",
                        verbose_name="Depo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sevkiyat",
                "verbose_name_plural": "Sevkiyatlar",
            },
        ),
        migrations.CreateModel(
            name="Waybill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "waybill_no",
                    models.CharField(max_length=50, verbose_name="İrsaliye No"),
                ),
                ("waybill_date", models.DateField(verbose_name="İrsaliye Tarihi")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.shipment",
                        verbose_name="Sevkiyat",
                    ),
                ),
            ],
            options={
                "verbose_name": "İrsaliye",
                "verbose_name_plural": "İrsaliyeler",
            },
        ),
        migrations.AddField(
            model_name="warehousestock",
            name="product_size",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.productcategorysizes",
                verbose_name="Ürün Boyutu",
            ),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="email",
            field=models.EmailField(
                blank=True, max_length=50, null=True, verbose_name="E-posta"
            ),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="fax",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Faks"
            ),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Telefon"
            ),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="tax_no",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Vergi No"
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="email",
            field=models.EmailField(
                blank=True, max_length=50, null=True, verbose_name="E-posta"
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="fax",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Faks"
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Telefon"
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="tax_no",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Vergi No"
            ),
        ),
        migrations.AlterField(
            model_name="warehousestock",
            name="stock",
            field=models.PositiveIntegerField(verbose_name="Stok"),
        ),
        migrations.CreateModel(
            name="WaybillProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="Miktar")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.products",
                        verbose_name="Ürün",
                    ),
                ),
                (
                    "product_size",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.productcategorysizes",
                        verbose_name="Ürün Boyutu",
                    ),
                ),
                (
                    "waybill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.waybill",
                        verbose_name="İrsaliye",
                    ),
                ),
            ],
            options={
                "verbose_name": "İrsaliye Ürün",
                "verbose_name_plural": "İrsaliye Ürünler",
            },
        ),
    ]
