# Generated by Django 5.0 on 2024-02-12 13:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "__first__"),
        ("schools", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscountCoupon",
            fields=[
                ("dc_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "discountName",
                    models.CharField(max_length=255, verbose_name="İndirim Adı"),
                ),
                (
                    "discountCouponCode",
                    models.CharField(
                        help_text="İndirim kupon kodunu giriniz.",
                        max_length=255,
                        verbose_name="İndirim Kupon Kodu",
                    ),
                ),
                (
                    "discountPerPerson",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Kişi başına indirim adedi giriniz. Örnek: A kişisi bu indirimden 1 kere yararlanabilir.",
                        verbose_name="Kişi Başı İndirim Hakkı",
                    ),
                ),
                (
                    "discountTotalNumber",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Toplam indirim adedi giriniz. Örnek: Bu indirim kodu toplamda 100 kere kullanılabilir.",
                        verbose_name="Toplam İndirim Adedi",
                    ),
                ),
                (
                    "discountRemainingNumber",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Kalan indirim adedi. Bu alan otomatik hesaplanacaktır Örnek: Bu indirim kodu 100 kere kullanılabilir. 50 kere kullanıldı. Kalan indirim adedi 50'dir.",
                        verbose_name="Kalan İndirim Adedi",
                    ),
                ),
                (
                    "discountMinAmount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="İndirim uygulanacak minimum sepet tutarını giriniz.",
                        max_digits=10,
                        verbose_name="Minimum Sepet Tutarı",
                    ),
                ),
                (
                    "discountType",
                    models.CharField(
                        choices=[("percentage", "Yüzde"), ("amount", "Tutar")],
                        default="percentage",
                        max_length=255,
                        verbose_name="İndirim Tipi",
                    ),
                ),
                (
                    "discountAmount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Yüzde için 0-100 arası değer giriniz.",
                        max_digits=10,
                        verbose_name="İndirim Tutarı",
                    ),
                ),
                (
                    "cargoDiscount",
                    models.BooleanField(
                        default=False,
                        help_text="Kargo indirimi uygulanacak mı?",
                        verbose_name="Kargo İndirimi",
                    ),
                ),
                (
                    "cargoDiscountAmount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        help_text="Uygulanacak kargo indirimi oranını giriniz.",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="Kargo İndirim Oranı",
                    ),
                ),
                (
                    "discountStartDate",
                    models.DateTimeField(
                        blank=True,
                        help_text="İndirim başlangıç tarihi giriniz. Boş bırakırsanız indirim anında aktif olur.",
                        null=True,
                        verbose_name="İndirim Başlangıç Tarihi",
                    ),
                ),
                (
                    "discountEndDate",
                    models.DateTimeField(
                        blank=True,
                        help_text="İndirim bitiş tarihi giriniz. Boş bırakırsanız indirim süresiz devam eder.",
                        null=True,
                        verbose_name="İndirim Bitiş Tarihi",
                    ),
                ),
                (
                    "discountStatus",
                    models.BooleanField(
                        default=True,
                        help_text="İndirim aktifliğini seçiniz. Bu alan seçtiğiniz tarih aralığına göre otomatik olarak güncellenecektir.",
                        verbose_name="İndirim Aktifliği",
                    ),
                ),
                (
                    "discountAdminDescription",
                    models.TextField(
                        blank=True,
                        help_text="İndirim açıklaması giriniz. Bu açıklamayı sadece adminler görecek.",
                        null=True,
                        verbose_name="Açıklama",
                    ),
                ),
                (
                    "discountCreatedDate",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="İndirim Oluşturulma Tarihi"
                    ),
                ),
                (
                    "discountUpdatedDate",
                    models.DateTimeField(
                        auto_now=True, verbose_name="İndirim Güncellenme Tarihi"
                    ),
                ),
                (
                    "campus",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Kampüs bazlı indirim uygulanacak kampüsleri seçiniz.",
                        related_name="discount_coupon",
                        to="schools.schoolcampus",
                        verbose_name="Kampüsler",
                    ),
                ),
                (
                    "member",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Öğrenci bazlı indirim uygulanacak öğrencileri seçiniz. (Öğrencinin bulunduğu kampüs Kampüsler alanında seçilmişse bu alan boş bırakılabilir.)",
                        related_name="discount_coupon",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Öğrenciler",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        help_text="Kampüs bazlı indirim uygulanacak okulu seçiniz.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discount_coupon",
                        to="schools.schools",
                        verbose_name="Okul",
                    ),
                ),
            ],
            options={
                "verbose_name": "İndirim Kuponu",
                "verbose_name_plural": "İndirim Kuponları",
            },
        ),
        migrations.CreateModel(
            name="DiscountCouponUsage",
            fields=[
                ("dcu_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "count_usage",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Kullanım Sayısı"
                    ),
                ),
                (
                    "discount",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="discounts.discountcoupon",
                        verbose_name="Kullanılan Kod",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanan Kişi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kupon Kullanım",
                "verbose_name_plural": "Kupon Kullanımları",
            },
        ),
        migrations.CreateModel(
            name="SpecialDiscount",
            fields=[
                ("sd_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "discountName",
                    models.CharField(max_length=255, verbose_name="İndirim Adı"),
                ),
                (
                    "discountPerPerson",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Kişi başına indirim adedi giriniz. Örnek: A kişisi bu indirimden 1 kere yararlanabilir.",
                        verbose_name="Kişi Başına İndirim Adedi",
                    ),
                ),
                (
                    "discountAdminDescription",
                    models.TextField(
                        blank=True,
                        help_text="İndirim açıklaması giriniz. Bu açıklamayı sadece adminler görecek.",
                        null=True,
                        verbose_name="Açıklama",
                    ),
                ),
                (
                    "discountDescription",
                    models.TextField(
                        blank=True,
                        help_text="İndirim açıklaması giriniz. Bu açıklamayı kullanı görecektir. Örnek: Seçili ürünlerde 2500₺ ve üzeri alışverişlerinize 10% (250₺) indirim fırsatı.",
                        null=True,
                        verbose_name="İndirim Açıklaması",
                    ),
                ),
                (
                    "discountMinAmount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="İndirim Uygulanacak Minimum Tutar",
                    ),
                ),
                (
                    "discountType",
                    models.CharField(
                        choices=[("percentage", "Yüzde"), ("amount", "Tutar")],
                        default="percentage",
                        max_length=255,
                        verbose_name="İndirim Tipi",
                    ),
                ),
                (
                    "discountAmount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Yüzde için 0-100 arası değer giriniz.",
                        max_digits=10,
                        verbose_name="İndirim Tutarı",
                    ),
                ),
                (
                    "cargoDiscount",
                    models.BooleanField(
                        default=False,
                        help_text="Kargo indirimi uygulanacak mı?",
                        verbose_name="Kargo İndirimi",
                    ),
                ),
                (
                    "cargoDiscountAmount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        help_text="Uygulanacak kargo indirimi oranını giriniz.",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="Kargo İndirim Oranı",
                    ),
                ),
                (
                    "discountStartDate",
                    models.DateTimeField(
                        blank=True,
                        help_text="İndirim başlangıç tarihi giriniz. Boş bırakırsanız indirim anında aktif olur.",
                        null=True,
                        verbose_name="İndirim Başlangıç Tarihi",
                    ),
                ),
                (
                    "discountEndDate",
                    models.DateTimeField(
                        blank=True,
                        help_text="İndirim bitiş tarihi giriniz. Boş bırakırsanız indirim süresiz devam eder.",
                        null=True,
                        verbose_name="İndirim Bitiş Tarihi",
                    ),
                ),
                (
                    "discountStatus",
                    models.BooleanField(
                        default=True,
                        help_text="İndirim aktifliğini seçiniz. Bu alan seçtiğiniz tarih aralığına göre otomatik olarak güncellenecektir.",
                        verbose_name="İndirim Aktifliği",
                    ),
                ),
                (
                    "discountCreatedDate",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="İndirim Oluşturulma Tarihi"
                    ),
                ),
                (
                    "discountUpdatedDate",
                    models.DateTimeField(
                        auto_now=True, verbose_name="İndirim Güncellenme Tarihi"
                    ),
                ),
                (
                    "campus",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Kampüs bazlı indirim uygulanacak kampüsleri seçiniz.",
                        related_name="special_discounts",
                        to="schools.schoolcampus",
                        verbose_name="Kampüsler",
                    ),
                ),
                (
                    "member",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Öğrenci bazlı indirim uygulanacak öğrencileri seçiniz. (Öğrencinin bulunduğu kampüs Kampüsler alanında seçilmişse bu alan boş bırakılabilir.)",
                        related_name="special_discounts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Öğrenciler",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Kampüs bazlı indirim uygulanacak ürünleri seçiniz. Boş bırakırsanız tüm ürünlerde indirim uygulanacaktır.",
                        related_name="special_discounts",
                        to="products.products",
                        verbose_name="Ürünler",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        help_text="Kampüs bazlı indirim uygulanacak okulu seçiniz.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="special_discounts",
                        to="schools.schools",
                        verbose_name="Okul",
                    ),
                ),
            ],
            options={
                "verbose_name": "Özel İndirim",
                "verbose_name_plural": "Özel İndirimler",
            },
        ),
        migrations.CreateModel(
            name="SpecialDiscountUsage",
            fields=[
                ("sdu_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "count_usage",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Kullanım Sayısı"
                    ),
                ),
                (
                    "discount",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="discounts.specialdiscount",
                        verbose_name="Kullanılan İndirim",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanan Kişi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Özel İndirim Kullanım",
                "verbose_name_plural": "Özel İndirim Kullanımları",
            },
        ),
    ]
