# Generated by Django 4.2.8 on 2023-12-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0016_alter_combinationproduct_options_and_more"),
        ("discounts", "0005_discountcoupon_discountremainingnumber_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="discountcoupon",
            options={
                "verbose_name": "İndirim Kuponu",
                "verbose_name_plural": "İndirim Kuponları",
            },
        ),
        migrations.RemoveField(
            model_name="discountcoupon",
            name="discountDescription",
        ),
        migrations.AlterField(
            model_name="discountcoupon",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                help_text="İndirim uygulanacak ürünleri seçiniz. Boş bırakırsanız tüm ürünlerde indirim uygulanacaktır.",
                related_name="discount_coupon",
                to="products.products",
                verbose_name="Ürünler",
            ),
        ),
        migrations.AlterField(
            model_name="specialdiscount",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                help_text="Kampüs bazlı indirim uygulanacak ürünleri seçiniz. Boş bırakırsanız tüm ürünlerde indirim uygulanacaktır.",
                related_name="special_discounts",
                to="products.products",
                verbose_name="Ürünler",
            ),
        ),
    ]
