# Generated by Django 4.2.8 on 2023-12-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discounts", "0007_remove_discountcoupon_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discountcoupon",
            name="discountMinAmount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="İndirim Uygulanması için Gereken Minimum Sepet Tutarı (0 : Tüm Sepetlere Uygulanacak)",
            ),
        ),
    ]
