# Generated by Django 4.2.8 on 2023-12-31 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0016_alter_combinationproduct_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Üretici Adı")),
                ("address", models.CharField(max_length=200, verbose_name="Adres")),
                ("tax_no", models.CharField(max_length=20, verbose_name="Vergi No")),
                ("email", models.EmailField(max_length=50, verbose_name="E-posta")),
                ("phone", models.CharField(max_length=20, verbose_name="Telefon")),
                ("fax", models.CharField(max_length=20, verbose_name="Faks")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Üretici",
                "verbose_name_plural": "Üreticiler",
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Tedarikçi Adı")),
                ("address", models.CharField(max_length=200, verbose_name="Adres")),
                ("tax_no", models.CharField(max_length=20, verbose_name="Vergi No")),
                ("email", models.EmailField(max_length=50, verbose_name="E-posta")),
                ("phone", models.CharField(max_length=20, verbose_name="Telefon")),
                ("fax", models.CharField(max_length=20, verbose_name="Faks")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tedarikçi",
                "verbose_name_plural": "Tedarikçiler",
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Depo Adı")),
                ("address", models.CharField(max_length=200, verbose_name="Adres")),
                ("phone", models.CharField(max_length=20, verbose_name="Telefon")),
                ("fax", models.CharField(max_length=20, verbose_name="Faks")),
            ],
            options={
                "verbose_name": "Depo",
                "verbose_name_plural": "Depolar",
            },
        ),
        migrations.CreateModel(
            name="WarehouseStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock", models.IntegerField(verbose_name="Stok")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.products",
                        verbose_name="Ürün",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.warehouse",
                        verbose_name="Depo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Depo Stok",
                "verbose_name_plural": "Depo Stokları",
                "unique_together": {("warehouse", "product")},
            },
        ),
    ]
