# Generated by Django 4.2.8 on 2023-12-31 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0002_shipment_waybill_warehousestock_product_size_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="waybillproduct",
            options={
                "verbose_name": "İrsaliye Kontrol",
                "verbose_name_plural": "İrsaliye Kontrolleri",
            },
        ),
        migrations.AddField(
            model_name="shipment",
            name="manufacturer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="warehouse.manufacturer",
                verbose_name="Üretici",
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="warehouse.supplier",
                verbose_name="Tedarikçi",
            ),
        ),
        migrations.AddField(
            model_name="waybillproduct",
            name="act_quantity",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Sayılan Miktar"
            ),
        ),
        migrations.AlterField(
            model_name="waybillproduct",
            name="quantity",
            field=models.PositiveIntegerField(verbose_name="Beklenen Miktar"),
        ),
    ]
