# Generated by Django 4.2.8 on 2023-12-31 19:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "warehouse",
            "0003_alter_waybillproduct_options_shipment_manufacturer_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shipment",
            name="address",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="fax",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="phone",
        ),
    ]
