# Generated by Django 4.2.6 on 2023-11-06 21:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_alter_products_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="products",
            options={
                "ordering": ["-product_created_at"],
                "permissions": [
                    ("view_bk_products", "Can view bkAdmin products"),
                    ("edit_bk_products", "Can edit bkAdmin products"),
                    ("view_girne_products", "Can view girneAdmin products"),
                    ("edit_girne_products", "Can edit girneAdmin products"),
                ],
                "verbose_name": "Ürünler",
                "verbose_name_plural": "Ürünler",
            },
        ),
    ]
