# Generated by Django 4.2.7 on 2023-11-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_alter_products_productsubcategoryid"),
    ]

    operations = [
        migrations.AddField(
            model_name="productdetails",
            name="product_short_desc",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productdetails",
            name="product_detail",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productdetails",
            name="product_find_size",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productdetails",
            name="product_info",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productdetails",
            name="product_measure",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productdetails",
            name="product_quality",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productdetails",
            name="product_size_table",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productdetails",
            name="product_suggestions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productdetails",
            name="product_video",
            field=models.TextField(blank=True, null=True),
        ),
    ]
