# Generated by Django 4.2.7 on 2023-11-11 21:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0013_alter_productdetails_product_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productcategory",
            name="school",
        ),
        migrations.RemoveField(
            model_name="productsubcategory",
            name="school",
        ),
    ]
