# Generated by Django 5.0 on 2024-02-12 13:45

import django.db.models.deletion
import support.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportTicket",
            fields=[
                (
                    "ticket_id",
                    models.SlugField(
                        editable=False,
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Destek No",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[("Kıyafet", "Kıyafet"), ("Kitap", "Kitap")],
                        max_length=100,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("Degisim", "Kıyafet/Değişim"),
                            ("Iade", "Kıyafet/İade"),
                            ("Iptal", "Kıyafet/İptal"),
                            ("Fatura", "Kıyafet/Fatura"),
                            ("Urun", "Kıyafet/Ürün"),
                            ("Siparis", "Kıyafet/Sipariş"),
                            ("Web", "Kıyafet/Web"),
                            ("Kargo", "Kıyafet/Kargo"),
                            ("Teslimat", "Kıyafet/Teslimat"),
                            ("Odeme", "Kıyafet/Ödeme"),
                            ("HataliUrun", "Kıyafet/Hatalı Ürün"),
                            ("EskiUrun", "Kıyafet/Eski Ürün"),
                            ("Kargolama", "Kitap/Kargolama"),
                            ("SipIptal", "Kitap/Sipariş İptal"),
                            ("KitapDegisim", "Kitap/Değişim"),
                            ("KitapIade", "Kitap/İade"),
                            ("KitapIptal", "Kitap/İptal"),
                            ("KitapKargo", "Kitap/Kargo"),
                            ("KitapTeslimat", "Kitap/Teslimat"),
                            ("KitapHataliUrun", "Kitap/Hatalı Ürün"),
                            ("KitapEksikUrun", "Kitap/Eksik Ürün"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Aktif"),
                            ("IN_PROGRESS", "Talebiniz İnceleniyor"),
                            ("CLOSED", "Çözüldü"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Destek Talebi",
                "verbose_name_plural": "Destek Talepleri",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SupportMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to=support.models.upload_location
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="support.supportticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Destek Talebi Mesajları",
                "verbose_name_plural": "Destek Talebi Mesajları",
                "ordering": ["created_at"],
            },
        ),
    ]
