# Generated by Django 4.2.6 on 2023-11-06 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0004_alter_member_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campus",
            fields=[
                ("campus_id", models.AutoField(primary_key=True, serialize=False)),
                ("FranchiseState", models.BooleanField()),
                ("Phone", models.CharField(max_length=255)),
                ("Email", models.EmailField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="CampusAddress",
            fields=[
                (
                    "CampusAddressID",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("FullAddress", models.CharField(max_length=255)),
                ("District", models.CharField(max_length=50)),
                ("City", models.CharField(max_length=50)),
                ("PostalCode", models.IntegerField()),
                ("AuthorizedFirstName", models.CharField(max_length=50)),
                ("AuthorizedLastName", models.CharField(max_length=50)),
                ("AuthorizedEmail", models.EmailField(max_length=100)),
                ("AuthorizedPhone", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Class",
            fields=[
                ("class_id", models.AutoField(primary_key=True, serialize=False)),
                ("ClassName", models.CharField(max_length=255)),
                ("ClassDescription", models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name="member",
            name="school",
        ),
        migrations.AlterField(
            model_name="member",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="Aktiflik Durumu"),
        ),
        migrations.CreateModel(
            name="StudentLevels",
            fields=[
                ("level_id", models.AutoField(primary_key=True, serialize=False)),
                ("LevelName", models.CharField(max_length=100)),
                (
                    "CampusID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="members.campus"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="campus",
            name="CampusAddressID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="members.campusaddress"
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="campus_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="members.campus",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="class_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="members.class",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="level_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="members.studentlevels",
            ),
        ),
    ]
