# Generated by Django 4.2.6 on 2023-11-06 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0005_campus_campusaddress_class_remove_member_school_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentlevels",
            name="CampusID",
        ),
        migrations.AlterField(
            model_name="member",
            name="campus_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name=""
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="class_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name=""
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="Staff Durumu"),
        ),
        migrations.AlterField(
            model_name="member",
            name="level_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name=""
            ),
        ),
        migrations.DeleteModel(
            name="Campus",
        ),
        migrations.DeleteModel(
            name="CampusAddress",
        ),
        migrations.DeleteModel(
            name="Class",
        ),
        migrations.DeleteModel(
            name="StudentLevels",
        ),
    ]
