# Generated by Django 4.2.7 on 2023-12-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0009_memberaddress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberaddress",
            name="PostalCode",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
