# Generated by Django 4.2.7 on 2023-12-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0010_alter_memberaddress_postalcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberaddress",
            name="AddressType",
            field=models.CharField(
                choices=[("Delivery", "Teslimat"), ("Invoice", "Fatura")],
                max_length=100,
            ),
        ),
    ]
