# Generated by Django 4.2.7 on 2023-12-03 13:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="district",
            options={"ordering": ["name"]},
        ),
    ]
