# Generated by Django 4.2.7 on 2023-12-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0006_studentlevels_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentlevels",
            name="LevelDescription",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="studentlevels",
            name="LevelName",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
