# Generated by Django 4.2.8 on 2023-12-15 07:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("schools", "0011_alter_schoolpopup_popup_title"),
        ("products", "0016_alter_combinationproduct_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampusBasedSpecialDiscount",
            fields=[
                ("cbsd_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "discountName",
                    models.CharField(max_length=255, verbose_name="İndirim Adı"),
                ),
                (
                    "discountPerPerson",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Kişi başına indirim adedi giriniz. Örnek: A kişisi bu indirimden 1 kere yararlanabilir.",
                        verbose_name="Kişi Başına İndirim Adedi",
                    ),
                ),
                (
                    "discountAdminDescription",
                    models.TextField(
                        blank=True,
                        help_text="İndirim açıklaması giriniz. Bu açıklamayı sadece adminler görecek.",
                        null=True,
                        verbose_name="Açıklama",
                    ),
                ),
                (
                    "discountDescription",
                    models.TextField(
                        blank=True,
                        help_text="İndirim açıklaması giriniz. Bu açıklamayı kullanı görecektir. Örnek: Seçili ürünlerde 2500₺ ve üzeri alışverişlerinize 10% (250₺) indirim fırsatı.",
                        null=True,
                        verbose_name="İndirim Açıklaması",
                    ),
                ),
                (
                    "discountMinAmount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="İndirim Uygulanacak Minimum Tutar",
                    ),
                ),
                (
                    "discountType",
                    models.CharField(
                        choices=[("percentage", "Yüzde"), ("amount", "Tutar")],
                        default="percentage",
                        max_length=255,
                        verbose_name="İndirim Tipi",
                    ),
                ),
                (
                    "discountAmount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Yüzde için 0-100 arası değer giriniz.",
                        max_digits=10,
                        verbose_name="İndirim Tutarı",
                    ),
                ),
                (
                    "cargoDiscount",
                    models.BooleanField(
                        default=False,
                        help_text="Kargo indirimi uygulanacak mı?",
                        verbose_name="Kargo İndirimi",
                    ),
                ),
                (
                    "cargoDiscountAmount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        help_text="Uygulanacak kargo indirimi oranını giriniz.",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="Kargo İndirim Oranı",
                    ),
                ),
                (
                    "discountStatus",
                    models.BooleanField(
                        default=True,
                        help_text="İndirim aktifliğini seçiniz.",
                        verbose_name="İndirim Aktifliği",
                    ),
                ),
                (
                    "discountStartDate",
                    models.DateField(
                        blank=True,
                        help_text="İndirim başlangıç tarihi giriniz. Boş bırakırsanız indirim anında aktif olur.",
                        null=True,
                        verbose_name="İndirim Başlangıç Tarihi",
                    ),
                ),
                (
                    "discountEndDate",
                    models.DateField(
                        blank=True,
                        help_text="İndirim bitiş tarihi giriniz. Boş bırakırsanız indirim süresiz devam eder.",
                        null=True,
                        verbose_name="İndirim Bitiş Tarihi",
                    ),
                ),
                (
                    "campus",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Kampüs bazlı indirim uygulanacak kampüsleri seçiniz.",
                        related_name="campus_based_special_discounts",
                        to="schools.schoolcampus",
                        verbose_name="Kampüsler",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Kampüs bazlı indirim uygulanacak ürünleri seçiniz.",
                        to="products.products",
                        verbose_name="Ürünler",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        help_text="Kampüs bazlı indirim uygulanacak okulu seçiniz.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schools.schools",
                        verbose_name="Okul",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kampüs Bazlı İndirim",
                "verbose_name_plural": "Kampüs Bazlı İndirimler",
            },
        ),
    ]
