# Generated by Django 4.2.8 on 2023-12-15 10:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0016_alter_combinationproduct_options_and_more"),
        ("schools", "0011_alter_schoolpopup_popup_title"),
        ("discounts", "0003_specialdiscount_delete_campusbasedspecialdiscount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="specialdiscount",
            old_name="cbsd_id",
            new_name="sd_id",
        ),
        migrations.CreateModel(
            name="DiscountCoupon",
            fields=[
                ("dc_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "discountName",
                    models.CharField(max_length=255, verbose_name="İndirim Adı"),
                ),
                (
                    "discountCouponCode",
                    models.CharField(
                        help_text="İndirim kupon kodunu giriniz.",
                        max_length=255,
                        verbose_name="İndirim Kupon Kodu",
                    ),
                ),
                (
                    "discountPerPerson",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Kişi başına indirim adedi giriniz. Örnek: A kişisi bu indirimden 1 kere yararlanabilir.",
                        verbose_name="Kişi Başına İndirim Adedi",
                    ),
                ),
                (
                    "discountAdminDescription",
                    models.TextField(
                        blank=True,
                        help_text="İndirim açıklaması giriniz. Bu açıklamayı sadece adminler görecek.",
                        null=True,
                        verbose_name="Açıklama",
                    ),
                ),
                (
                    "discountDescription",
                    models.TextField(
                        blank=True,
                        help_text="İndirim açıklaması giriniz. Bu açıklamayı kullanı görecektir. Örnek: Seçili ürünlerde 2500₺ ve üzeri alışverişlerinize 10% (250₺) indirim fırsatı.",
                        null=True,
                        verbose_name="İndirim Açıklaması",
                    ),
                ),
                (
                    "discountMinAmount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="İndirim Uygulanacak Minimum Tutar",
                    ),
                ),
                (
                    "discountType",
                    models.CharField(
                        choices=[("percentage", "Yüzde"), ("amount", "Tutar")],
                        default="percentage",
                        max_length=255,
                        verbose_name="İndirim Tipi",
                    ),
                ),
                (
                    "discountAmount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Yüzde için 0-100 arası değer giriniz.",
                        max_digits=10,
                        verbose_name="İndirim Tutarı",
                    ),
                ),
                (
                    "cargoDiscount",
                    models.BooleanField(
                        default=False,
                        help_text="Kargo indirimi uygulanacak mı?",
                        verbose_name="Kargo İndirimi",
                    ),
                ),
                (
                    "cargoDiscountAmount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        help_text="Uygulanacak kargo indirimi oranını giriniz.",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="Kargo İndirim Oranı",
                    ),
                ),
                (
                    "discountStartDate",
                    models.DateTimeField(
                        blank=True,
                        help_text="İndirim başlangıç tarihi giriniz. Boş bırakırsanız indirim anında aktif olur.",
                        null=True,
                        verbose_name="İndirim Başlangıç Tarihi",
                    ),
                ),
                (
                    "discountEndDate",
                    models.DateTimeField(
                        blank=True,
                        help_text="İndirim bitiş tarihi giriniz. Boş bırakırsanız indirim süresiz devam eder.",
                        null=True,
                        verbose_name="İndirim Bitiş Tarihi",
                    ),
                ),
                (
                    "discountStatus",
                    models.BooleanField(
                        default=True,
                        help_text="İndirim aktifliğini seçiniz. Bu alan seçtiğiniz tarih aralığına göre otomatik olarak güncellenecektir.",
                        verbose_name="İndirim Aktifliği",
                    ),
                ),
                (
                    "campus",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Kampüs bazlı indirim uygulanacak kampüsleri seçiniz.",
                        to="schools.schoolcampus",
                        verbose_name="Kampüsler",
                    ),
                ),
                (
                    "member",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Öğrenci bazlı indirim uygulanacak öğrencileri seçiniz. (Öğrencinin bulunduğu kampüs Kampüsler alanında seçilmişse bu alan boş bırakılabilir.)",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Öğrenciler",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Kampüs bazlı indirim uygulanacak ürünleri seçiniz.",
                        to="products.products",
                        verbose_name="Ürünler",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        help_text="Kampüs bazlı indirim uygulanacak okulu seçiniz.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schools.schools",
                        verbose_name="Okul",
                    ),
                ),
            ],
            options={
                "verbose_name": "Özel İndirim",
                "verbose_name_plural": "Özel İndirimler",
            },
        ),
    ]
