# Generated by Django 4.2.7 on 2023-12-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discounts", "0009_discountcoupon_discountcreateddate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discountcoupon",
            name="discountMinAmount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="İndirim uygulanacak minimum sepet tutarını giriniz.",
                max_digits=10,
                verbose_name="Minimum Sepet Tutarı",
            ),
        ),
    ]
