# Generated by Django 4.2.7 on 2023-12-16 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("discounts", "0010_alter_discountcoupon_discountminamount"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscountCouponUsage",
            fields=[
                ("dcu_id", models.AutoField(primary_key=True, serialize=False)),
                ("count", models.PositiveIntegerField(default=0)),
                (
                    "discount",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="discounts.discountcoupon",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Kupon Kullanım",
                "verbose_name_plural": "Kupon Kullanımları",
            },
        ),
    ]
