# Generated by Django 4.2.6 on 2023-11-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schools",
            options={
                "ordering": ["school_name"],
                "verbose_name": "Okullar",
                "verbose_name_plural": "Okullar",
            },
        ),
        migrations.AlterField(
            model_name="schoolslider",
            name="slider_title",
            field=models.CharField(default="Default Title", max_length=255),
        ),
    ]
