# Generated by Django 4.2.6 on 2023-11-06 20:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0002_alter_schools_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schoolpopup",
            options={
                "permissions": [
                    ("view_schools", "Can view Pants products"),
                    ("edit_schools", "Can edit Pants products"),
                    ("view_tshirts_products", "Can view T-shirts products"),
                    ("edit_tshirts_products", "Can edit T-shirts products"),
                ],
                "verbose_name": "Popup Ayarları",
                "verbose_name_plural": "Popup Ayarları",
            },
        ),
    ]
