# Generated by Django 4.2.6 on 2023-11-06 20:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0003_alter_schoolpopup_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schoolpopup",
            options={
                "verbose_name": "Popup Ayarları",
                "verbose_name_plural": "Popup Ayarları",
            },
        ),
    ]
