# Generated by Django 4.2.7 on 2023-11-11 22:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0004_alter_schoolpopup_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schoolcampus",
            name="id",
        ),
        migrations.AddField(
            model_name="schoolcampus",
            name="capmus_id",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
