# Generated by Django 4.2.7 on 2023-12-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0007_studentlevels_leveldescription_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="ClassDescription",
            field=models.TextField(blank=True, null=True),
        ),
    ]
