# Generated by Django 4.2.8 on 2023-12-13 15:46

from django.db import migrations, models
import schools.models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0008_alter_class_classdescription"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolpopup",
            name="popup_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=schools.models.upload_location_settings
            ),
        ),
    ]
