# Generated by Django 4.2.8 on 2023-12-13 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0009_schoolpopup_popup_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolpopup",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="school_popup",
                to="schools.schools",
            ),
        ),
    ]
