# Generated by Django 4.2.8 on 2023-12-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0010_alter_schoolpopup_school"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolpopup",
            name="popup_title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
