# Generated by Django 4.2.8 on 2023-12-09 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0016_alter_combinationproduct_options_and_more"),
        ("orders", "0004_remove_orderaddress_buyerlastname_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderproducts",
            old_name="ProductID",
            new_name="Product",
        ),
        migrations.RenameField(
            model_name="orderproducts",
            old_name="CreatedAt",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="orderproducts",
            old_name="UpdatedAt",
            new_name="updated_at",
        ),
        migrations.RemoveField(
            model_name="orderproducts",
            name="ProductType",
        ),
        migrations.AddField(
            model_name="orderproducts",
            name="is_combined_product",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="orderproducts",
            name="is_set_product",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="orderproducts",
            name="size_stock",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.sizebasedstocks",
            ),
        ),
        migrations.CreateModel(
            name="OrderShipping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="orders.orders"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="orders.orders"
                    ),
                ),
            ],
        ),
    ]
