# Generated by Django 4.2.8 on 2023-12-09 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0016_alter_combinationproduct_options_and_more"),
        ("orders", "0005_rename_productid_orderproducts_product_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderproducts",
            options={
                "verbose_name": "Sipariş Ürünleri",
                "verbose_name_plural": "Sipariş Ürünleri",
            },
        ),
        migrations.AlterModelOptions(
            name="orders",
            options={"verbose_name": "Siparişler", "verbose_name_plural": "Siparişler"},
        ),
        migrations.RemoveField(
            model_name="orderproducts",
            name="size_stock",
        ),
        migrations.AddField(
            model_name="orderproducts",
            name="discounted_sale_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Özel İndirimli Fiyat",
            ),
        ),
        migrations.AddField(
            model_name="orderproducts",
            name="prod_old_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Ürün Eski Fiyat",
            ),
        ),
        migrations.AddField(
            model_name="orderproducts",
            name="prod_sale_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Ürün Satış Fiyatı",
            ),
        ),
        migrations.AddField(
            model_name="orderproducts",
            name="selected_size",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.sizebasedstocks",
                verbose_name="Seçilen Beden",
            ),
        ),
        migrations.AlterField(
            model_name="orderproducts",
            name="Order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.orders",
                verbose_name="Sipariş No",
            ),
        ),
        migrations.AlterField(
            model_name="orderproducts",
            name="Product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="products.products",
                verbose_name="Ürün",
            ),
        ),
        migrations.AlterField(
            model_name="orderproducts",
            name="Quantity",
            field=models.IntegerField(default=1, verbose_name="Adet"),
        ),
        migrations.AlterField(
            model_name="orderproducts",
            name="is_combined_product",
            field=models.BooleanField(default=False, verbose_name="Kombin Ürün"),
        ),
        migrations.AlterField(
            model_name="orderproducts",
            name="is_set_product",
            field=models.BooleanField(default=False, verbose_name="Set Ürün"),
        ),
    ]
