# Generated by Django 4.2.8 on 2023-12-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0007_remove_orders_actualdeliverydate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="OrderCargoFee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Kargo Ücreti",
            ),
        ),
    ]
