# Generated by Django 4.2.8 on 2023-12-10 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0010_alter_orderaddress_addresstype_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orders",
            options={
                "ordering": ["-OrderDate"],
                "verbose_name": "Siparişler",
                "verbose_name_plural": "Siparişler",
            },
        ),
        migrations.CreateModel(
            name="TempOrderDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("city_name", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=100)),
                ("district_name", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("zip", models.CharField(max_length=20)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("invoice_city", models.CharField(max_length=100)),
                ("invoice_city_name", models.CharField(max_length=100)),
                ("invoice_district", models.CharField(max_length=100)),
                ("invoice_district_name", models.CharField(max_length=255)),
                ("invoice_address", models.TextField()),
                ("invoice_phone", models.CharField(max_length=20)),
                ("invoice_email", models.EmailField(max_length=254)),
                ("comp_name", models.CharField(max_length=255)),
                ("tax_office", models.CharField(max_length=255)),
                ("tax_number", models.CharField(max_length=100)),
                ("order_notes", models.TextField(blank=True, null=True)),
                ("different_address", models.BooleanField(default=False)),
                ("save_address", models.BooleanField(default=False)),
                ("conversation_id", models.CharField(max_length=100)),
                ("token", models.CharField(max_length=255)),
                (
                    "Member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
