# Generated by Django 4.2.8 on 2023-12-10 14:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0011_alter_orders_options_temporderdetails"),
    ]

    operations = [
        migrations.RenameField(
            model_name="temporderdetails",
            old_name="Member",
            new_name="member",
        ),
    ]
