# Generated by Django 4.2.8 on 2023-12-10 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0013_remove_temporderdetails_member"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="temporderdetails",
            name="id",
        ),
        migrations.AddField(
            model_name="temporderdetails",
            name="member",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="temporderdetails",
            name="tod_id",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
