# Generated by Django 4.2.8 on 2023-12-28 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0016_alter_orderaddress_order_alter_orderpayment_order_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReturnRequests",
            fields=[
                (
                    "ReturnID",
                    models.SlugField(
                        editable=False,
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="İade Talep No",
                    ),
                ),
                (
                    "ReturnStatus",
                    models.CharField(
                        choices=[
                            ("İade Talebi Alındı", "İade Talebi Alındı"),
                            ("Talep İnceleniyor", "Talep İnceleniyor"),
                            ("Talep Onaylandı", "Talep Onaylandı"),
                            ("İade Bekleniyor", "İade Bekleniyor"),
                            ("İade İnceleniyor", "İade İnceleniyor"),
                            ("İade Edildi", "İade Edildi"),
                        ],
                        default="İade Talebi Alındı",
                        max_length=100,
                        verbose_name="İade Talep Durumu",
                    ),
                ),
                (
                    "ReturnPaymentAmount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="İade Edilecek Tutar",
                    ),
                ),
                (
                    "ReturnPaymentStatus",
                    models.CharField(
                        choices=[
                            ("Bekliyor", "Bekliyor"),
                            ("Ödeme Yapıldı", "Ödeme Yapıldı"),
                            ("Ödeme Yapılmadı", "Ödeme Yapılmadı"),
                        ],
                        default="Bekliyor",
                        max_length=100,
                        verbose_name="İade Ödeme Durumu",
                    ),
                ),
                (
                    "ReturnPaymentDate",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="İade Ödeme Tarihi"
                    ),
                ),
                (
                    "ReturnReason",
                    models.CharField(
                        choices=[
                            ("Ürün Arızalı", "Ürün Arızalı"),
                            ("Ürün Hasarlı", "Ürün Hasarlı"),
                            ("Ürün Yanlış", "Ürün Yanlış"),
                            ("Ürün Eksik", "Ürün Eksik"),
                            ("Ürün Değişim", "Ürün Değişim"),
                            ("Ürün İade", "Ürün İade"),
                        ],
                        default="Ürün Arızalı",
                        max_length=100,
                        verbose_name="İade Nedeni",
                    ),
                ),
                (
                    "ReturnNote",
                    models.TextField(blank=True, null=True, verbose_name="İade Notu"),
                ),
                (
                    "ReturnRequestDate",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="İade Talep Tarihi"
                    ),
                ),
                (
                    "ReturnApprovedDate",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="İade Onay Tarihi"
                    ),
                ),
                (
                    "ReturnCompletedDate",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="İade Tamamlanma Tarihi"
                    ),
                ),
                (
                    "Member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="TC No",
                    ),
                ),
                (
                    "OrderID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.orders",
                        verbose_name="Sipariş No",
                    ),
                ),
            ],
            options={
                "verbose_name": "İade Talebi",
                "verbose_name_plural": "İade Talepleri",
                "ordering": ["-ReturnRequestDate"],
            },
        ),
        migrations.CreateModel(
            name="ReturnProducts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ProductPrice",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Ürün Fiyatı",
                    ),
                ),
                (
                    "PaidAmount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Ödenen Tutar",
                    ),
                ),
                (
                    "ReturnQuantity",
                    models.IntegerField(default=1, verbose_name="Ürün Adedi"),
                ),
                (
                    "OrderProductID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.orderproducts",
                        verbose_name="Sipariş Ürün No",
                    ),
                ),
                (
                    "ReturnID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.returnrequests",
                        verbose_name="İade Talep No",
                    ),
                ),
            ],
            options={
                "verbose_name": "İade Ürün",
                "verbose_name_plural": "İade Ürünler",
                "ordering": ["-ReturnID"],
            },
        ),
    ]
