# Generated by Django 5.0 on 2024-02-12 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("discounts", "__first__"),
        ("products", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "cart_id",
                    models.BigAutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "SpecialDiscountStatus",
                    models.CharField(
                        choices=[
                            ("Özel İndirim Yok", "Özel İndirim Yok"),
                            ("Özel İndirim Uygulandı", "Özel İndirim Uygulandı"),
                            ("Admin İndirimi Uygulandı", "Admin İndirimi Uygulandı"),
                            ("Kampanya İndirimi", "Kampanya İndirimi"),
                        ],
                        default="Özel İndirim Yok",
                        max_length=100,
                        verbose_name="Özel İndirim",
                    ),
                ),
                (
                    "SpecialDiscount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Özel İndirim Tutarı",
                    ),
                ),
                (
                    "CouponCode",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Uygulanan Kupon Kodu",
                    ),
                ),
                (
                    "CouponDiscount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Kupon İndirimi",
                    ),
                ),
                (
                    "SpecialDiscountApplied",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="discounts.specialdiscount",
                        verbose_name="Uygulanan İndirim",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_cart",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sepet",
                "verbose_name_plural": "Sepetler",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CartItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_combined_product", models.BooleanField(default=False)),
                ("is_set_product", models.BooleanField(default=False)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_cart",
                        to="cart.cart",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.products",
                    ),
                ),
                (
                    "size_stock",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.sizebasedstocks",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sepet Ürün",
                "verbose_name_plural": "Sepet Ürünler",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CombinedProductChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cart_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cart.cartitems"
                    ),
                ),
                (
                    "combination_product_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.combinationproduct",
                    ),
                ),
                (
                    "selected_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.products",
                    ),
                ),
                (
                    "size_stock",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.sizebasedstocks",
                    ),
                ),
            ],
        ),
    ]
