# Generated by Django 4.2.7 on 2023-12-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0006_cart_couponcode_cart_coupondiscount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="SpecialDiscountStatus",
            field=models.CharField(
                choices=[
                    ("Özel İndirim Yok", "Özel İndirim Yok"),
                    ("Özel İndirim Uygulandı", "Özel İndirim Uygulandı"),
                    ("Admin İndirimi Uygulandı", "Admin İndirimi Uygulandı"),
                    ("Kampanya İndirimi", "Kampanya İndirimi"),
                ],
                default="Özel İndirim Yok",
                max_length=100,
                verbose_name="Özel İndirim",
            ),
        ),
    ]
