# Generated by Django 4.2.6 on 2023-11-04 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Orders",
            fields=[
                ("OrderID", models.AutoField(primary_key=True, serialize=False)),
                ("OrderType", models.CharField(max_length=100)),
                ("InvoiceInfoID", models.IntegerField()),
                ("TotalAmount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("OrderStatus", models.CharField(max_length=100)),
                ("OrderProductQuantity", models.IntegerField()),
                ("OrderTaxAmount", models.IntegerField()),
                ("TotalDiscountAmount", models.IntegerField()),
                ("OrderCargoFee", models.IntegerField()),
                ("GiftAmount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "SpecialDiscount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("PaymentInfoID", models.IntegerField()),
                ("WarehouseID", models.IntegerField()),
                ("WarehouseStatus", models.CharField(max_length=100)),
                ("CargoStatus", models.CharField(max_length=100)),
                ("CargoTrackNumber", models.IntegerField()),
                ("EstimatedDeliveryDate", models.DateField()),
                ("ActualDeliveryDate", models.DateField()),
                ("DeliveryInfoID", models.IntegerField()),
                ("ExternalReferenceID", models.IntegerField()),
                ("OrderDate", models.DateTimeField(auto_now_add=True)),
                ("LastUpdatedAt", models.DateTimeField(auto_now=True)),
                (
                    "Member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderProducts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ProductType", models.CharField(max_length=100)),
                ("Quantity", models.IntegerField(default=1)),
                ("CreatedAt", models.DateTimeField(auto_now_add=True)),
                ("UpdatedAt", models.DateTimeField(auto_now=True)),
                (
                    "Order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="orders.orders"
                    ),
                ),
                (
                    "ProductID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.products",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("BuyerName", models.CharField(max_length=100)),
                ("BuyerLastName", models.CharField(max_length=100)),
                (
                    "AddressType",
                    models.CharField(
                        choices=[("Invoice", "Fatura"), ("Delivery", "Teslimat")],
                        max_length=100,
                    ),
                ),
                ("City", models.CharField(max_length=100)),
                ("District", models.CharField(max_length=100)),
                ("FullAddress", models.CharField(max_length=100)),
                ("PostalCode", models.IntegerField()),
                ("PhoneNumber", models.IntegerField()),
                ("EMail", models.EmailField(max_length=254)),
                ("CreatedAt", models.DateTimeField(auto_now_add=True)),
                ("UpdatedAt", models.DateTimeField(auto_now=True)),
                (
                    "Order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="orders.orders"
                    ),
                ),
            ],
        ),
    ]
