# Generated by Django 5.0 on 2024-02-12 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "__first__"),
        ("schools", "__first__"),
        ("store", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderProducts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_combined_product",
                    models.BooleanField(default=False, verbose_name="Kombin Ürün"),
                ),
                (
                    "is_set_product",
                    models.BooleanField(default=False, verbose_name="Set Ürün"),
                ),
                ("Quantity", models.IntegerField(default=1, verbose_name="Adet")),
                (
                    "prod_old_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Ürün Eski Fiyat",
                    ),
                ),
                (
                    "prod_sale_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Ürün Satış Fiyatı",
                    ),
                ),
                (
                    "discounted_sale_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Özel İndirimli Fiyat",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "Product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.products",
                        verbose_name="Ürün",
                    ),
                ),
                (
                    "selected_size",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.sizebasedstocks",
                        verbose_name="Seçilen Beden",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sipariş Ürünleri",
                "verbose_name_plural": "Sipariş Ürünleri",
            },
        ),
        migrations.CreateModel(
            name="OrderCombinedProductChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "combination_product_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.combinationproduct",
                    ),
                ),
                (
                    "selected_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.products",
                    ),
                ),
                (
                    "size_stock",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.sizebasedstocks",
                    ),
                ),
                (
                    "order_prod",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.orderproducts",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "OrderID",
                    models.SlugField(
                        editable=False,
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Sipariş No",
                    ),
                ),
                (
                    "OrderType",
                    models.CharField(
                        choices=[
                            ("Normal Sipariş", "Normal Sipariş"),
                            ("Bayi Siparişi", "Bayi Siparişi"),
                        ],
                        default="Normal Sipariş",
                        max_length=100,
                        verbose_name="Sipariş Türü",
                    ),
                ),
                (
                    "OrderStatus",
                    models.CharField(
                        choices=[
                            ("Sipariş Alındı", "Sipariş Alındı"),
                            ("Teslim Edildi", "Teslim Edildi"),
                            ("İptal Edildi", "İptal Edildi"),
                            ("İade Edildi", "İade Edildi"),
                            ("Değişim", "Değişim"),
                        ],
                        default="Sipariş Alındı",
                        max_length=100,
                        verbose_name="Sipariş Durumu",
                    ),
                ),
                (
                    "OrderWarehouseStatus",
                    models.BooleanField(default=False, verbose_name="Depo Durumu"),
                ),
                (
                    "OrderCargoFee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Kargo Ücreti",
                    ),
                ),
                (
                    "SpecialDiscountStatus",
                    models.CharField(
                        choices=[
                            ("Özel İndirim Yok", "Özel İndirim Yok"),
                            ("Öğrenci İndirimi", "Öğrenci İndirimi"),
                            ("Kampüs İndirimi", "Kampüs İndirimi"),
                            ("Kampanya İndirimi", "Kampanya İndirimi"),
                        ],
                        default="Özel İndirim Yok",
                        max_length=100,
                        verbose_name="Özel İndirim",
                    ),
                ),
                (
                    "SpecialDiscount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Özel İndirim Tutarı",
                    ),
                ),
                (
                    "CouponCode",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Uygulanan Kupon Kodu",
                    ),
                ),
                (
                    "CouponDiscount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Kupon İndirimi",
                    ),
                ),
                (
                    "OrderNote",
                    models.TextField(
                        blank=True, null=True, verbose_name="Sipariş Notları"
                    ),
                ),
                ("OrderDate", models.DateTimeField(auto_now_add=True)),
                ("LastUpdatedAt", models.DateTimeField(auto_now=True)),
                (
                    "Member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="TC No",
                    ),
                ),
                (
                    "MemberClass",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schools.class",
                        verbose_name="Üye Sınıfı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Siparişler",
                "verbose_name_plural": "Siparişler",
                "ordering": ["-OrderDate"],
            },
        ),
        migrations.AddField(
            model_name="orderproducts",
            name="Order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_order_items",
                to="orders.orders",
                verbose_name="Sipariş No",
            ),
        ),
        migrations.CreateModel(
            name="OrderPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "PaymentProvider",
                    models.CharField(
                        choices=[("iyzico", "iyzico"), ("Diğer", "Diğer")],
                        default="iyzico",
                        max_length=100,
                    ),
                ),
                (
                    "PaymentStatus",
                    models.CharField(
                        choices=[
                            ("Ödeme Alındı", "Ödeme Alındı"),
                            ("Ödeme Alınmadı", "Ödeme Alınmadı"),
                        ],
                        default="Ödeme Alındı",
                        max_length=100,
                    ),
                ),
                ("PaymentId", models.CharField(max_length=255)),
                ("ConversationId", models.CharField(max_length=255)),
                (
                    "FraudStatus",
                    models.CharField(
                        choices=[
                            ("-1", "Yüksek Fraud Riski"),
                            ("0", "Fraud İhtimali"),
                            ("1", "Düşük Fraud Riski"),
                        ],
                        default="1",
                        max_length=100,
                    ),
                ),
                ("Installment", models.PositiveIntegerField(blank=True, null=True)),
                ("Currency", models.CharField(default="TRY", max_length=10)),
                ("Price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("PaidPrice", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "iyziCommissionRateAmount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "iyziCommissionFee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "MerchantPayoutAmount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("CardType", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "CardAssociation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("CardFamily", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "Order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_payment",
                        to="orders.orders",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "AddressType",
                    models.CharField(
                        choices=[("Teslimat", "Teslimat"), ("Fatura", "Fatura")],
                        max_length=100,
                    ),
                ),
                ("recipient_name", models.CharField(max_length=255)),
                ("recipient_lastname", models.CharField(max_length=255)),
                ("Country", models.CharField(default="Türkiye", max_length=100)),
                ("FullAddress", models.TextField()),
                ("PostalCode", models.PositiveIntegerField(blank=True, null=True)),
                ("PhoneNumber", models.IntegerField()),
                ("EMail", models.EmailField(max_length=254)),
                ("comp_name", models.CharField(blank=True, max_length=255, null=True)),
                ("tax_office", models.CharField(blank=True, max_length=255, null=True)),
                ("tax_no", models.PositiveBigIntegerField(blank=True, null=True)),
                ("CreatedAt", models.DateTimeField(auto_now_add=True)),
                ("UpdatedAt", models.DateTimeField(auto_now=True)),
                (
                    "City",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.city"
                    ),
                ),
                (
                    "District",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.district"
                    ),
                ),
                (
                    "Order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_address",
                        to="orders.orders",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderShipping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="orders.orders"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReturnRequests",
            fields=[
                (
                    "ReturnID",
                    models.SlugField(
                        editable=False,
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="İade Talep No",
                    ),
                ),
                (
                    "ReturnStatus",
                    models.CharField(
                        choices=[
                            ("İade Talebi Alındı", "İade Talebi Alındı"),
                            ("Talep İnceleniyor", "Talep İnceleniyor"),
                            ("Talep Onaylandı", "Talep Onaylandı"),
                            ("İade Bekleniyor", "İade Bekleniyor"),
                            ("İade İnceleniyor", "İade İnceleniyor"),
                            ("İade Edildi", "İade Edildi"),
                        ],
                        default="İade Talebi Alındı",
                        max_length=100,
                        verbose_name="İade Talep Durumu",
                    ),
                ),
                (
                    "ReturnPaymentAmount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="İade Edilecek Tutar",
                    ),
                ),
                (
                    "ReturnPaymentStatus",
                    models.CharField(
                        choices=[
                            ("Bekliyor", "Bekliyor"),
                            ("Ödeme Yapıldı", "Ödeme Yapıldı"),
                            ("Ödeme Yapılmadı", "Ödeme Yapılmadı"),
                        ],
                        default="Bekliyor",
                        max_length=100,
                        verbose_name="İade Ödeme Durumu",
                    ),
                ),
                (
                    "ReturnPaymentDate",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="İade Ödeme Tarihi"
                    ),
                ),
                (
                    "ReturnReason",
                    models.CharField(
                        choices=[
                            ("Ürün Arızalı", "Ürün Arızalı"),
                            ("Ürün Hasarlı", "Ürün Hasarlı"),
                            ("Ürün Yanlış", "Ürün Yanlış"),
                            ("Ürün Eksik", "Ürün Eksik"),
                            ("Ürün Değişim", "Ürün Değişim"),
                            ("Ürün İade", "Ürün İade"),
                        ],
                        default="Ürün Arızalı",
                        max_length=100,
                        verbose_name="İade Nedeni",
                    ),
                ),
                (
                    "ReturnNote",
                    models.TextField(blank=True, null=True, verbose_name="İade Notu"),
                ),
                (
                    "ReturnRequestDate",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="İade Talep Tarihi"
                    ),
                ),
                (
                    "ReturnApprovedDate",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="İade Onay Tarihi"
                    ),
                ),
                (
                    "ReturnCompletedDate",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="İade Tamamlanma Tarihi"
                    ),
                ),
                (
                    "Member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="TC No",
                    ),
                ),
                (
                    "OrderID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.orders",
                        verbose_name="Sipariş No",
                    ),
                ),
            ],
            options={
                "verbose_name": "İade Talebi",
                "verbose_name_plural": "İade Talepleri",
                "ordering": ["-ReturnRequestDate"],
            },
        ),
        migrations.CreateModel(
            name="ReturnProducts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ProductPrice",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Ürün Fiyatı",
                    ),
                ),
                (
                    "PaidAmount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Ödenen Tutar",
                    ),
                ),
                (
                    "ReturnQuantity",
                    models.IntegerField(default=1, verbose_name="Ürün Adedi"),
                ),
                (
                    "OrderProductID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.orderproducts",
                        verbose_name="Sipariş Ürün No",
                    ),
                ),
                (
                    "ReturnID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.returnrequests",
                        verbose_name="İade Talep No",
                    ),
                ),
            ],
            options={
                "verbose_name": "İade Ürün",
                "verbose_name_plural": "İade Ürünler",
                "ordering": ["-ReturnID"],
            },
        ),
        migrations.CreateModel(
            name="TempOrderDetails",
            fields=[
                ("tod_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("city_name", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=100)),
                ("district_name", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("zip", models.CharField(max_length=20)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("invoice_city", models.CharField(max_length=100)),
                ("invoice_city_name", models.CharField(max_length=100)),
                ("invoice_district", models.CharField(max_length=100)),
                ("invoice_district_name", models.CharField(max_length=255)),
                ("invoice_address", models.TextField()),
                ("invoice_phone", models.CharField(max_length=20)),
                ("invoice_email", models.EmailField(max_length=254)),
                ("comp_name", models.CharField(max_length=255)),
                ("tax_office", models.CharField(max_length=255)),
                ("tax_number", models.CharField(max_length=100)),
                ("order_notes", models.TextField(blank=True, null=True)),
                ("different_address", models.BooleanField(default=False)),
                ("save_address", models.BooleanField(default=False)),
                ("conversation_id", models.CharField(max_length=100)),
                ("token", models.CharField(max_length=255)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
