# Generated by Django 4.2.6 on 2023-11-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_alter_orderproducts_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderproducts",
            name="Quantity",
            field=models.IntegerField(default=1),
        ),
    ]
