# Generated by Django 4.2.8 on 2023-12-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_alter_orderproducts_options_alter_orders_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orders",
            name="ActualDeliveryDate",
        ),
        migrations.RemoveField(
            model_name="orders",
            name="CargoStatus",
        ),
        migrations.RemoveField(
            model_name="orders",
            name="CargoTrackNumber",
        ),
        migrations.RemoveField(
            model_name="orders",
            name="DeliveryInfoID",
        ),
        migrations.RemoveField(
            model_name="orders",
            name="EstimatedDeliveryDate",
        ),
        migrations.RemoveField(
            model_name="orders",
            name="ExternalReferenceID",
        ),
        migrations.RemoveField(
            model_name="orders",
            name="GiftAmount",
        ),
        migrations.RemoveField(
            model_name="orders",
            name="InvoiceInfoID",
        ),
        migrations.RemoveField(
            model_name="orders",
            name="OrderProductQuantity",
        ),
        migrations.RemoveField(
            model_name="orders",
            name="OrderTaxAmount",
        ),
        migrations.RemoveField(
            model_name="orders",
            name="PaymentInfoID",
        ),
        migrations.RemoveField(
            model_name="orders",
            name="TotalAmount",
        ),
        migrations.RemoveField(
            model_name="orders",
            name="TotalDiscountAmount",
        ),
        migrations.RemoveField(
            model_name="orders",
            name="WarehouseID",
        ),
        migrations.RemoveField(
            model_name="orders",
            name="WarehouseStatus",
        ),
        migrations.AddField(
            model_name="orders",
            name="CouponCode",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Uygulanan Kupon Kodu",
            ),
        ),
        migrations.AddField(
            model_name="orders",
            name="CouponDiscount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Kupon İndirimi",
            ),
        ),
        migrations.AddField(
            model_name="orders",
            name="OrderNote",
            field=models.TextField(
                blank=True, null=True, verbose_name="Sipariş Notları"
            ),
        ),
        migrations.AddField(
            model_name="orders",
            name="SpecialDiscountStatus",
            field=models.CharField(
                choices=[
                    ("Özel İndirim Yok", "Özel İndirim Yok"),
                    ("Öğrenci İndirimi", "Öğrenci İndirimi"),
                    ("Kampüs İndirimi", "Kampüs İndirimi"),
                    ("Kampanya İndirimi", "Kampanya İndirimi"),
                ],
                default="Özel İndirim Yok",
                max_length=100,
                verbose_name="Özel İndirim",
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="OrderID",
            field=models.SlugField(
                editable=False,
                max_length=10,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="Sipariş No",
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="OrderStatus",
            field=models.CharField(
                choices=[
                    ("Sipariş Alındı", "Sipariş Alındı"),
                    ("Teslim Edildi", "Teslim Edildi"),
                    ("İptal Edildi", "İptal Edildi"),
                    ("İade Edildi", "İade Edildi"),
                    ("Değişim", "Değişim"),
                ],
                default="Sipariş Alındı",
                max_length=100,
                verbose_name="Sipariş Durumu",
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="OrderType",
            field=models.CharField(
                choices=[
                    ("Normal Sipariş", "Normal Sipariş"),
                    ("Bayi Siparişi", "Bayi Siparişi"),
                ],
                default="Normal Sipariş",
                max_length=100,
                verbose_name="Sipariş Türü",
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="SpecialDiscount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Özel İndirim Tutarı",
            ),
        ),
    ]
