# Generated by Django 4.2.8 on 2023-12-09 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0008_alter_orders_ordercargofee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderproducts",
            name="Order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_order_items",
                to="orders.orders",
                verbose_name="Sipariş No",
            ),
        ),
    ]
