# Generated by Django 4.2.8 on 2023-12-10 14:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0012_rename_member_temporderdetails_member"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="temporderdetails",
            name="member",
        ),
    ]
