# Generated by Django 4.2.8 on 2023-12-13 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "orders",
            "0015_orderpayment_cardassociation_orderpayment_cardfamily_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderaddress",
            name="Order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_address",
                to="orders.orders",
            ),
        ),
        migrations.AlterField(
            model_name="orderpayment",
            name="Order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_payment",
                to="orders.orders",
            ),
        ),
        migrations.AlterField(
            model_name="orderpayment",
            name="PaymentStatus",
            field=models.CharField(
                choices=[
                    ("Ödeme Alındı", "Ödeme Alındı"),
                    ("Ödeme Alınmadı", "Ödeme Alınmadı"),
                ],
                default="Ödeme Alındı",
                max_length=100,
            ),
        ),
    ]
