# Generated by Django 5.0 on 2024-01-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0017_returnrequests_returnproducts"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="OrderWarehouseStatus",
            field=models.BooleanField(default=False, verbose_name="Depo Durumu"),
        ),
    ]
