# Generated by Django 5.0 on 2024-01-21 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0018_orders_orderwarehousestatus"),
        ("schools", "0011_alter_schoolpopup_popup_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="MemberClass",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="schools.class",
                verbose_name="Üye Sınıfı",
            ),
        ),
    ]
