# Generated by Django 4.2.7 on 2023-11-12 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0014_remove_productcategory_school_and_more"),
        ("cart", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="id",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="product",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="quantity",
        ),
        migrations.AddField(
            model_name="cart",
            name="cart_id",
            field=models.BigAutoField(
                default=1, primary_key=True, serialize=False, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cartitems",
            name="is_combined_product",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="cartitems",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_cart",
                to="cart.cart",
            ),
        ),
        migrations.CreateModel(
            name="CombinedProductChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cart_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cart.cartitems"
                    ),
                ),
                (
                    "combination_product_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.combinationproduct",
                    ),
                ),
                (
                    "selected_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.products",
                    ),
                ),
            ],
        ),
    ]
