# Generated by Django 4.2.8 on 2023-12-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0004_cartitems_size_stock_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitems",
            name="is_set_product",
            field=models.BooleanField(default=False),
        ),
    ]
