# Generated by Django 4.2.8 on 2023-12-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0005_cartitems_is_set_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="CouponCode",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Uygulanan Kupon Kodu",
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="CouponDiscount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Kupon İndirimi",
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="SpecialDiscount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Özel İndirim Tutarı",
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="SpecialDiscountStatus",
            field=models.CharField(
                choices=[
                    ("Özel İndirim Yok", "Özel İndirim Yok"),
                    ("Öğrenci İndirimi", "Öğrenci İndirimi"),
                    ("Kampüs İndirimi", "Kampüs İndirimi"),
                    ("Kampanya İndirimi", "Kampanya İndirimi"),
                ],
                default="Özel İndirim Yok",
                max_length=100,
                verbose_name="Özel İndirim",
            ),
        ),
    ]
