# Generated by Django 4.2.7 on 2023-12-27 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cart", "0008_cart_specialdiscountapplied"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="member_cart",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
