# Generated by Django 4.2.6 on 2023-11-03 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campus",
            fields=[
                ("campus_id", models.AutoField(primary_key=True, serialize=False)),
                ("FranchiseState", models.BooleanField()),
                ("Phone", models.CharField(max_length=255)),
                ("Email", models.EmailField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="CampusAddress",
            fields=[
                (
                    "CampusAddressID",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("FullAddress", models.CharField(max_length=255)),
                ("District", models.CharField(max_length=50)),
                ("City", models.CharField(max_length=50)),
                ("PostalCode", models.IntegerField()),
                ("AuthorizedFirstName", models.CharField(max_length=50)),
                ("AuthorizedLastName", models.CharField(max_length=50)),
                ("AuthorizedEmail", models.EmailField(max_length=100)),
                ("AuthorizedPhone", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Class",
            fields=[
                ("class_id", models.AutoField(primary_key=True, serialize=False)),
                ("ClassName", models.CharField(max_length=255)),
                ("ClassDescription", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="StudentLevels",
            fields=[
                ("level_id", models.AutoField(primary_key=True, serialize=False)),
                ("LevelName", models.CharField(max_length=100)),
                (
                    "CampusID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="members.campus"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="campus",
            name="CampusAddressID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="members.campusaddress"
            ),
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("member_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Username"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=150, verbose_name="Ad"),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=150, verbose_name="Soyad"),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Doğum Tarihi"
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("Öğrenci", "Öğrenci"),
                            ("Mevcut Öğrenci", "Mevcut Öğrenci"),
                            ("Kurumsal", "Kurumsal"),
                            ("Kurum Admin", "Kurum Admin"),
                            ("SuperUser", "SuperUser"),
                        ],
                        max_length=100,
                        verbose_name="Kullanıcı Tipi",
                    ),
                ),
                (
                    "user_gender",
                    models.CharField(
                        choices=[("Erkek", "Erkek"), ("Kız", "Kız")],
                        max_length=100,
                        verbose_name="Cinsiyet",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktiflik Durumu"),
                ),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="Aktiflik Durumu"),
                ),
                (
                    "ip_address",
                    models.CharField(max_length=45, verbose_name="IP Adres"),
                ),
                (
                    "season",
                    models.IntegerField(
                        choices=[
                            (2000, 2000),
                            (2001, 2001),
                            (2002, 2002),
                            (2003, 2003),
                            (2004, 2004),
                            (2005, 2005),
                            (2006, 2006),
                            (2007, 2007),
                            (2008, 2008),
                            (2009, 2009),
                            (2010, 2010),
                            (2011, 2011),
                            (2012, 2012),
                            (2013, 2013),
                            (2014, 2014),
                            (2015, 2015),
                            (2016, 2016),
                            (2017, 2017),
                            (2018, 2018),
                            (2019, 2019),
                            (2020, 2020),
                            (2021, 2021),
                            (2022, 2022),
                            (2023, 2023),
                            (2024, 2024),
                        ],
                        default=2023,
                        verbose_name="Sezon",
                    ),
                ),
                (
                    "campus_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.campus",
                    ),
                ),
                (
                    "class_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.class",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "level_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.studentlevels",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Üyeler",
                "verbose_name_plural": "Üyeler",
            },
        ),
    ]
