# Generated by Django 4.2.6 on 2023-10-23 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Members",
            fields=[
                ("memberID", models.AutoField(primary_key=True, serialize=False)),
                ("userType", models.CharField(max_length=20)),
                ("identification", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("firstName", models.CharField(max_length=255)),
                ("lastName", models.CharField(max_length=255)),
                ("phoneNumber", models.IntegerField()),
                ("email", models.CharField(max_length=255)),
                ("birthDate", models.DateTimeField()),
                ("gender", models.CharField(max_length=10)),
                ("weight", models.DecimalField(decimal_places=2, max_digits=5)),
                ("height", models.DecimalField(decimal_places=2, max_digits=4)),
                ("brandID", models.IntegerField()),
                ("vendorID", models.IntegerField()),
                ("campusID", models.IntegerField()),
                ("levelName", models.CharField(max_length=20)),
                ("classID", models.IntegerField()),
                ("registrationDate", models.DateTimeField()),
                ("lastUpdated", models.DateTimeField()),
                ("isActive", models.BooleanField()),
                ("ipAdress", models.CharField(max_length=45)),
                ("registrationState", models.CharField(max_length=20)),
                ("additionalData", models.JSONField()),
                ("Season", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="MemberAddress",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("adressLine1", models.CharField(max_length=256)),
                ("adressLine2", models.CharField(max_length=256)),
                ("city", models.CharField(max_length=256)),
                ("country", models.CharField(max_length=256)),
                ("phoneNumber", models.IntegerField()),
                (
                    "memberID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.members",
                    ),
                ),
            ],
        ),
    ]
