# Generated by Django 4.2.6 on 2023-10-23 21:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MemberAddress",
        ),
        migrations.DeleteModel(
            name="Members",
        ),
    ]
