# Generated by Django 4.2.6 on 2023-11-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("Öğrenci", "Öğrenci"),
                    ("Mevcut Öğrenci", "Mevcut Öğrenci"),
                    ("Kurumsal", "Kurumsal"),
                    ("Kurum Admin", "Kurum Admin"),
                    ("SuperUser", "SuperUser"),
                ],
                default="Öğrenci",
                max_length=100,
                verbose_name="Kullanıcı Tipi",
            ),
        ),
    ]
