# Generated by Django 4.2.7 on 2023-11-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "members",
            "0006_remove_studentlevels_campusid_alter_member_campus_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="campus_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="class_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="level_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
