# Generated by Django 4.2.7 on 2023-11-11 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0005_remove_schoolcampus_id_schoolcampus_capmus_id"),
        ("members", "0007_alter_member_campus_id_alter_member_class_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="campus_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="schools.schoolcampus",
            ),
        ),
    ]
