# Generated by Django 4.2.7 on 2023-12-03 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0008_alter_member_campus_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "AddressType",
                    models.CharField(
                        choices=[("Invoice", "Fatura"), ("Delivery", "Teslimat")],
                        max_length=100,
                    ),
                ),
                ("recipient_name", models.CharField(max_length=255)),
                ("recipient_lastname", models.CharField(max_length=255)),
                ("Country", models.CharField(default="Türkiye", max_length=100)),
                ("City", models.CharField(max_length=100)),
                ("District", models.CharField(max_length=100)),
                ("FullAddress", models.TextField()),
                ("PostalCode", models.PositiveIntegerField()),
                ("PhoneNumber", models.IntegerField()),
                ("EMail", models.EmailField(max_length=254)),
                ("comp_name", models.CharField(blank=True, max_length=255, null=True)),
                ("tax_office", models.CharField(blank=True, max_length=255, null=True)),
                ("tax_no", models.PositiveBigIntegerField(blank=True, null=True)),
                ("CreatedAt", models.DateTimeField(auto_now_add=True)),
                ("UpdatedAt", models.DateTimeField(auto_now=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
