# Generated by Django 4.2.7 on 2023-12-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0012_alter_memberaddress_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberaddress",
            name="City",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="memberaddress",
            name="District",
            field=models.CharField(max_length=100),
        ),
    ]
