# Generated by Django 4.2.7 on 2023-12-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0014_alter_memberaddress_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="phone_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
