# Generated by Django 4.2.7 on 2023-12-04 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0008_alter_class_classdescription"),
        ("members", "0015_alter_member_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="class_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="schools.class",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="level_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="schools.studentlevels",
            ),
        ),
    ]
