# Generated by Django 4.2.8 on 2023-12-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0016_alter_member_class_id_alter_member_level_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="registration_date",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Kayıt Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="E-Posta"
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="phone_number",
            field=models.IntegerField(blank=True, null=True, verbose_name="Telefon"),
        ),
        migrations.AlterField(
            model_name="member",
            name="username",
            field=models.CharField(max_length=100, unique=True, verbose_name="TC No"),
        ),
    ]
