# Generated by Django 5.0 on 2024-01-24 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0019_orders_memberclass"),
    ]

    operations = [
        migrations.CreateModel(
            name="CargoProvider",
            fields=[
                (
                    "CargoProviderID",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Cargo Provider ID",
                    ),
                ),
                (
                    "Name",
                    models.CharField(max_length=100, verbose_name="Provider Name"),
                ),
                (
                    "Description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "ContactEmail",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Contact Email",
                    ),
                ),
                (
                    "TelephoneNumber",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Telephone Number",
                    ),
                ),
                (
                    "WebsiteURL",
                    models.URLField(blank=True, null=True, verbose_name="Website URL"),
                ),
            ],
            options={
                "verbose_name": "Kargo Sağlayıcıları",
                "verbose_name_plural": "Kargo Sağlayıcıları",
            },
        ),
        migrations.CreateModel(
            name="Cargos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "TrackingNumber",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="KTN Numarası",
                    ),
                ),
                (
                    "MOKNumber",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="MÖK Numarası",
                    ),
                ),
                (
                    "CargoTakenDate",
                    models.DateField(verbose_name="Kargoya Verilme Tarihi"),
                ),
                (
                    "EstimatedDeliveryDate",
                    models.DateField(
                        blank=True, null=True, verbose_name="Tahmini Teslim Tarihi"
                    ),
                ),
                (
                    "CargoArrivalDate",
                    models.DateField(verbose_name="Kargo Teslim Tarihi"),
                ),
                (
                    "DeliveryStatus",
                    models.CharField(
                        choices=[
                            ("Teslim Edildi", "Teslim Edildi"),
                            ("Dağıtıma Çıktı", "Dağıtıma Çıktı"),
                            ("Teslim Edilemedi", "Teslim Edilemedi"),
                            ("Kargo Aktarım Sürecinde", "Kargo Aktarım Sürecinde"),
                        ],
                        default="Kargo Aktarım Sürecinde",
                        max_length=100,
                        verbose_name="Teslimat Durumu",
                    ),
                ),
                (
                    "CargoProvider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cargo.cargoprovider",
                        verbose_name="Kargo Sağlayıcı",
                    ),
                ),
                (
                    "OrderID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.orders",
                        verbose_name="Sipariş ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sipariş Kargoları",
                "verbose_name_plural": "Sipariş Kargoları",
            },
        ),
    ]
