# Generated by Django 4.2.6 on 2023-11-03 08:43

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CombinationProduct",
            fields=[
                ("CProductID", models.AutoField(primary_key=True, serialize=False)),
                ("SProductInfo", models.JSONField(blank=True, null=True)),
                ("CProductQuantity", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "ProductCategoryID",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("CategoryName", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ProductCategorySizes",
            fields=[
                ("CategorySizeID", models.AutoField(primary_key=True, serialize=False)),
                ("ProductSize", models.CharField(max_length=100)),
                (
                    "ProductCategoryID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.productcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductPrice",
            fields=[
                ("PriceID", models.AutoField(primary_key=True, serialize=False)),
                ("SalePrice", models.DecimalField(decimal_places=2, max_digits=10)),
                ("StrikedPrice", models.IntegerField(blank=True, null=True)),
                ("DiscountRatio", models.IntegerField(blank=True, null=True)),
                ("DiscountPrice", models.IntegerField(blank=True, null=True)),
                (
                    "DiscountType",
                    models.IntegerField(
                        blank=True,
                        choices=[(0, "0%"), (10, "10%"), (20, "20%")],
                        null=True,
                    ),
                ),
                ("TaxPrice", models.CharField(max_length=100)),
                ("CombinePriceInfo", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="ProductStock",
            fields=[
                ("StockID", models.AutoField(primary_key=True, serialize=False)),
                ("RealStock", models.IntegerField()),
                ("SaleStock", models.IntegerField()),
                ("ReservedStock", models.IntegerField()),
                ("AcceptStock", models.IntegerField()),
                ("ReturnStock", models.IntegerField()),
                ("CancelStock", models.IntegerField()),
                ("PreproductionStock", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="SetProduct",
            fields=[
                ("SetID", models.AutoField(primary_key=True, serialize=False)),
                ("SProductInfo", models.JSONField()),
                ("SProductQuantity", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                ("product_created_at", models.DateTimeField(auto_created=True)),
                ("ProductID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("Set", "Set"),
                            ("Kombin", "Kombin"),
                            ("Tekil", "Tekil"),
                        ],
                        default="Tekil",
                        max_length=100,
                    ),
                ),
                ("product_production_name", models.CharField(max_length=255)),
                ("product_name", models.CharField(max_length=255)),
                ("product_web_name", models.CharField(max_length=255)),
                ("product_production_date", models.DateField()),
                ("SKU_code", models.CharField(max_length=100)),
                ("barcode", models.CharField(max_length=100)),
                ("model_code", models.CharField(max_length=100)),
                ("product_color", models.CharField(max_length=100)),
                ("book_type", models.CharField(max_length=100)),
                (
                    "product_state",
                    models.CharField(
                        choices=[("Aktif", "Aktif"), ("Pasif", "Pasif")],
                        default="Aktif",
                        max_length=100,
                    ),
                ),
                ("product_genre", models.CharField(max_length=100)),
                ("product_class", models.CharField(max_length=100)),
                ("product_level", models.CharField(max_length=100)),
                (
                    "product_image",
                    models.FileField(
                        blank=True, null=True, upload_to=products.models.upload_location
                    ),
                ),
                ("product_measure_unit", models.CharField(max_length=100)),
                ("product_last_update", models.DateTimeField(auto_now=True)),
                ("product_season", models.DateField()),
                ("product_change_limit", models.JSONField(null=True)),
                (
                    "CategorySizeID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.productcategorysizes",
                    ),
                ),
                (
                    "PriceID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.productprice",
                    ),
                ),
                (
                    "ProductCategoryID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.productcategory",
                    ),
                ),
                (
                    "StockID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.productstock",
                    ),
                ),
            ],
        ),
    ]
