# Generated by Django 4.2.6 on 2023-11-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productprice",
            name="CombinePriceInfo",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productprice",
            name="DiscountType",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productprice",
            name="TaxPrice",
            field=models.CharField(
                blank=True,
                choices=[(0, "0%"), (10, "10%"), (20, "20%")],
                max_length=100,
                null=True,
            ),
        ),
    ]
