# Generated by Django 4.2.6 on 2023-10-24 19:41

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="combinationproduct",
            name="SProductInfo",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productprice",
            name="DiscountPrice",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productprice",
            name="DiscountRatio",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productprice",
            name="DiscountType",
            field=models.IntegerField(
                blank=True, choices=[(0, "0%"), (10, "10%"), (20, "20%")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="productprice",
            name="StrikedPrice",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="products",
            name="product_change_limit",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="products",
            name="product_created_at",
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name="products",
            name="product_image",
            field=models.FileField(
                blank=True, null=True, upload_to=products.models.upload_location
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="product_last_update",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="products",
            name="product_state",
            field=models.CharField(
                choices=[("Aktif", "Aktif"), ("Pasif", "Pasif")],
                default="Aktif",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="product_type",
            field=models.CharField(
                choices=[("Set", "Set"), ("Kombin", "Kombin"), ("Tekil", "Tekil")],
                default="Tekil",
                max_length=100,
            ),
        ),
    ]
