# Generated by Django 4.2.6 on 2023-11-03 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_remove_products_product_season_products_season_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="products",
            options={
                "ordering": ["-product_created_at"],
                "verbose_name": "Ürünler",
                "verbose_name_plural": "Ürünler",
            },
        ),
        migrations.RemoveField(
            model_name="products",
            name="PriceID",
        ),
        migrations.RemoveField(
            model_name="products",
            name="StockID",
        ),
        migrations.CreateModel(
            name="ProductSizeStock",
            fields=[
                (
                    "ProductSizeStockID",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("RealStock", models.IntegerField()),
                ("SaleStock", models.IntegerField()),
                ("ReservedStock", models.IntegerField()),
                ("AcceptStock", models.IntegerField()),
                ("ReturnStock", models.IntegerField()),
                ("CancelStock", models.IntegerField()),
                ("PreproductionStock", models.IntegerField()),
                (
                    "ProductCategorySizeID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.productcategorysizes",
                    ),
                ),
                (
                    "ProductID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.products",
                    ),
                ),
            ],
        ),
    ]
