# Generated by Django 4.2.6 on 2023-11-03 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_alter_products_options_remove_products_priceid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productsizestock",
            name="ProductCategorySizeID",
        ),
        migrations.RemoveField(
            model_name="productsizestock",
            name="ProductID",
        ),
        migrations.AddField(
            model_name="products",
            name="PriceID",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.productprice",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="products",
            name="StockID",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.productstock",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="products",
            name="product_sizes",
            field=models.ManyToManyField(blank=True, to="products.productsizestock"),
        ),
        migrations.AddField(
            model_name="productsizestock",
            name="ProductCategorySize",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.productcategorysizes",
            ),
            preserve_default=False,
        ),
    ]
