# Generated by Django 4.2.6 on 2023-11-06 18:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_remove_products_school_management"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="products",
            options={
                "ordering": ["-product_created_at"],
                "verbose_name": "Ürünler",
                "verbose_name_plural": "Ürünler",
            },
        ),
    ]
