# Generated by Django 4.2.6 on 2023-11-03 14:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_remove_productsizestock_productcategorysizeid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="product_sizes",
        ),
        migrations.DeleteModel(
            name="ProductSizeStock",
        ),
    ]
