# Generated by Django 4.2.6 on 2023-11-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_remove_products_product_sizes_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="products",
            options={
                "ordering": ["-product_created_at"],
                "permissions": [
                    ("view_bk_products", "Can view bkAdmin products"),
                    ("edit_bk_products", "Can edit bkAdmin products"),
                    ("view_girne_products", "Can view girneAdmin products"),
                    ("edit_girne_products", "Can edit girneAdmin products"),
                ],
                "verbose_name": "Ürünler",
                "verbose_name_plural": "Ürünler",
            },
        ),
        migrations.AddField(
            model_name="products",
            name="school_management",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
