# Generated by Django 4.2.6 on 2023-11-07 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_alter_products_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="ProductSubCategoryID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_subcategory",
                to="products.productsubcategory",
            ),
        ),
    ]
