# Generated by Django 4.2.6 on 2023-11-03 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_alter_products_options_products_school_management"),
    ]

    operations = [
        migrations.CreateModel(
            name="SizeBasedStocks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("real_stock", models.IntegerField()),
                ("sale_stock", models.IntegerField()),
                ("reserved_stock", models.IntegerField()),
                ("accept_stock", models.IntegerField()),
                ("return_stock", models.IntegerField()),
                ("cancel_stock", models.IntegerField()),
                ("preproduction_stock", models.IntegerField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.products",
                    ),
                ),
                (
                    "size",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.productcategorysizes",
                    ),
                ),
            ],
        ),
    ]
