# Generated by Django 4.2.6 on 2023-11-03 16:36

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_rename_product_sizebasedstocks_products"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_image",
                    models.FileField(
                        blank=True, null=True, upload_to=products.models.upload_location
                    ),
                ),
                (
                    "products",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.products",
                    ),
                ),
            ],
        ),
    ]
