# Generated by Django 4.2.6 on 2023-11-03 16:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0010_productimages"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="CategorySizeID",
        ),
        migrations.RemoveField(
            model_name="products",
            name="StockID",
        ),
    ]
