# Generated by Django 4.2.7 on 2023-11-09 16:39

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0004_alter_schoolpopup_options"),
        ("products", "0010_alter_productdetails_product_detail_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productsubcategory",
            name="school",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="schools.schools",
            ),
        ),
        migrations.AlterField(
            model_name="productdetails",
            name="product_detail",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Ürün Bilgileri"
            ),
        ),
    ]
