# Generated by Django 4.2.7 on 2023-11-09 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0004_alter_schoolpopup_options"),
        ("products", "0011_productsubcategory_school_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcategory",
            name="school",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="schools.schools",
            ),
        ),
    ]
