# Generated by Django 4.2.6 on 2023-11-03 16:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0012_productprices_remove_products_priceid_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductStock",
        ),
        migrations.AlterModelOptions(
            name="productimages",
            options={
                "verbose_name": "Ürün Görselleri",
                "verbose_name_plural": "Ürün Görselleri",
            },
        ),
        migrations.AlterModelOptions(
            name="productprices",
            options={"verbose_name": "Ürün Fiyat", "verbose_name_plural": "Ürün Fiyat"},
        ),
        migrations.AlterModelOptions(
            name="sizebasedstocks",
            options={
                "verbose_name": "Ürün Beden & Stok",
                "verbose_name_plural": "Ürün Beden & Stok",
            },
        ),
    ]
