# Generated by Django 4.2.6 on 2023-11-03 17:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0013_delete_productstock_alter_productimages_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="product_image",
        ),
    ]
