# Generated by Django 4.2.7 on 2023-11-27 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0005_remove_schoolcampus_id_schoolcampus_capmus_id"),
        ("products", "0014_remove_productcategory_school_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productprices",
            name="campusPrice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="schools.schoolcampus",
            ),
        ),
    ]
