# Generated by Django 4.2.6 on 2023-11-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0014_remove_products_product_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="SKU_code",
        ),
        migrations.RemoveField(
            model_name="products",
            name="barcode",
        ),
        migrations.AddField(
            model_name="sizebasedstocks",
            name="SKU_code",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sizebasedstocks",
            name="barcode",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
