# Generated by Django 4.2.7 on 2023-12-02 10:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0015_productprices_campusprice"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="combinationproduct",
            options={
                "verbose_name": "Kombin Ürünler",
                "verbose_name_plural": "Kombin Ürünler",
            },
        ),
        migrations.AlterModelOptions(
            name="setproduct",
            options={
                "verbose_name": "Set Ürünler",
                "verbose_name_plural": "Set Ürünler",
            },
        ),
    ]
